services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${MASTER_DB_USER}
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD}
      POSTGRES_DB: ${MASTER_DB_NAME}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_USER: ${AUTH_DB_USER}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      CORE_DB_NAME: ${CORE_DB_NAME}
      CORE_DB_USER: ${CORE_DB_USER}
      CORE_DB_PASSWORD: ${CORE_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${MASTER_DB_USER} -d ${MASTER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5


  gateway:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docs:/usr/share/nginx/html/docs:ro
    depends_on:
      auth:
        condition: service_started
      ingestor:
        condition: service_started
      core:
        condition: service_started
      frontend:
        condition: service_started
    restart: always

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./services/frontend:/app

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      valkey:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://${AUTH_DB_USER}:${AUTH_DB_PASSWORD}@db:5432/${AUTH_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - VALKEY_ADDR=${VALKEY_ADDR}
      - WORKER_SYSTEM_KEY=${WORKER_SYSTEM_KEY}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "8080:8080"
    volumes:
      - ./services/auth:/app

  ingestor:
    build:
      context: ./services/ingestor
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      valkey:
        condition: service_started
      garage:
        condition: service_started
    environment:
      - PORT=8080
      - VALKEY_ADDR=${VALKEY_ADDR}
      - STORAGE_ENDPOINT=garage:3900
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "8082:8080"
    volumes:
      - ./services/ingestor:/app

  core:
    build:
      context: ./services/core
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${CORE_DB_USER}:${CORE_DB_PASSWORD}@db:5432/${CORE_DB_NAME}
      - VALKEY_ADDR=${VALKEY_ADDR}
      - PORT=8080
      - AUTH_SERVICE_URL=http://gateway/auth
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "8081:8080"
    volumes:
      - ./services/core:/app

  customs-parser:
    build:
      context: ./services/customs-parser
      dockerfile: Dockerfile.dev
    restart: on-failure
    environment:
      - PORT=8085
    ports:
      - "8085:8085"
    volumes:
      - ./services/customs-parser:/app

  adapter-worker:
    build:
      context: ./services/adapter-worker
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - CORE_URL=http://gateway/api
      - ANPR_URL=http://anpr:8000/recognize
      - VALKEY_ADDR=${VALKEY_ADDR}
      - STORAGE_ENDPOINT=garage:3900
      - STORAGE_BUCKET=${STORAGE_BUCKET_NAME}
      - STORAGE_ACCESS_KEY=local-admin
      - STORAGE_SECRET_KEY=local-admin
      - WORKER_API_KEY=${WORKER_SYSTEM_KEY}
      - PYTHONUNBUFFERED=1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - valkey
      - core
      - garage
    volumes:
      - ./services/adapter-worker:/app

  # anpr:
  #   build:
  #     context: ./services/anpr
  #     dockerfile: Dockerfile.dev
  #   restart: unless-stopped
  #   environment:
  #     - TORCH_FORCE_WEIGHTS_ONLY_LOAD=0
  #     - PYTHONUNBUFFERED=1
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - nomeroff_models_cache:/root/.nomeroff_net
  #     - ./services/anpr:/app

  valkey:
    image: valkey/valkey:8.0-alpine
    ports:
      - "6379:6379"
    restart: always

  garage:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    environment:
      - GARAGE_RPC_SECRET=${STORAGE_SECRET}
      - GARAGE_ADMIN_TOKEN=${STORAGE_ROOT_PASSWORD}
      - GARAGE_ALLOW_WORLD_READABLE_SECRETS=true
    volumes:
      - ./infra/garage/garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    ports:
      - "3900:3900" # S3 API
      - "3901:3901" # RPC
      - "3902:3902" # Web Access
      - "3903:3903" # Admin API

  webui:
    image: khairul169/garage-webui:latest
    restart: unless-stopped
    volumes:
      - ./infra/garage/garage.toml:/etc/garage.toml:ro
    depends_on:
      - garage
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
      ADMIN_TOKEN: ${STORAGE_ACCESS_KEY} 
    ports:
      - 3909:3909
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./infra/otel/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889" # Prometheus Exporter

volumes:
  postgres_data:
  garage_meta:
  garage_data:
  nomeroff_models_cache:
  pgadmin-data:
